name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run rollup
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: kodi-in-progress.js
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
